deploys

diff --git a/.github/workflows/scm-cicd.yml b/.github/workflows/scm-cicd.yml
--- a/.github/workflows/scm-cicd.yml
+++ b/.github/workflows/scm-cicd.yml
@@ -22,6 +22,23 @@ jobs:
       - name: Install dependencies
         run: yarn install
 
+      - name: Run tests and calculate pass percentage
+        id: test
+        run: |
+          yarn test -- --json > test-results.json || true
+          PASS=$(cat test-results.json | jq -r '.numPassedTests')
+          TOTAL=$(cat test-results.json | jq -r '.numTotalTests')
+          PASS_PERCENT=$((PASS * 100 / TOTAL))
+          echo "Passed tests: $PASS / $TOTAL"
+          echo "Pass percentage: $PASS_PERCENT%"
+          echo "::set-output name=pass_percent::$PASS_PERCENT"
+
+      - name: Check pass percentage and stop action on failure
+        if: ${{ steps.test.outputs.pass_percent < 30 }}
+        run: |
+          echo "Pass percentage is less than 30%. Stopping the action."
+          exit 1
+
       - name: Build the project
         run: yarn build
 
@@ -48,15 +65,86 @@ jobs:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
       - name: Ensure target directory exists
-        run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "mkdir -p /home/ubuntu/app && chown -R ubuntu:ubuntu /home/ubuntu/app"
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            mkdir -p /home/ubuntu/app
+            chown -R ubuntu:ubuntu /home/ubuntu/app
 
       - name: Copy files to EC2
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.EC2_IP }}
-          username: ubuntu
+          username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           source: "build/*"
           target: "/home/ubuntu/app/"
+
+      - name: Create .env file
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            cat <<EOF > /home/ubuntu/app/build/configs/.env.staging
+            NODE_ENV=${{ secrets.NODE_ENV }}
+            PORT=${{ secrets.PORT }}
+            LOG_LEVEL=${{ secrets.LOG_LEVEL }}
+            MONGODB_URL=${{ secrets.MONGODB_URL}}
+            EOF
+
+      - name: Start Application
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            #!/bin/bash
+
+            # Check if nvm is installed
+            if [ -s "$HOME/.nvm/nvm.sh" ]; then
+              source "$HOME/.nvm/nvm.sh"
+            elif [ -s "/usr/local/nvm/nvm.sh" ]; then
+              source "/usr/local/nvm/nvm.sh"
+            else
+              echo "nvm is not installed."
+              exit 1
+            fi
+
+            # Verify yarn installation
+            if ! command -v yarn &> /dev/null; then
+              echo "Yarn could not be found"
+              exit 1
+            fi
+
+            cd /home/ubuntu/app/build
+            echo "Checking directory contents..."
+            ls -alh # Lists all files in the current directory
+
+            # Check if server.js exists in the correct directory
+            if [ ! -f ./src/server.js ]; then
+              echo "server.js not found in ./src/"
+              exit 1
+            fi
+
+            # Install Dependencies
+            echo "Installing dependencies..."
+            yarn install
+
+            # Check if the PM2 process is running
+            if pm2 show SCM > /dev/null; then
+              echo "Application is running. Restarting..."
+              pm2 restart SCM
+            else
+              echo "Application is not running. Starting..."
+              pm2 start ./src/server.js --name SCM
+            fi
